#CTD tidying
libraries needed are tidyverse
```{r}
library(tidyverse)
```

uploading files into environment 
```{r}
CTD_MFS_0524<-read.csv2("CTD_MFS_0524.csv")
CTD_MFS_0924<-read.csv2("CTD_MFS_0924.csv")
CTD_MFS_1224<-read.csv2("CTD_MFS_1224.csv")
CTD_Lok2_0424<-read.csv2("CTD_Lok2_0424.csv")
CTD_Lok2_0924<-read.csv2("CTD_Lok2_0924.csv")
CTD_Lok1_1224<-read.csv2("CTD_Lok1_1224.csv")
CTD_Lok1_0924<-read.csv2("CTD_Lok1_0924.csv")
CTD_Kvavik_0424<-read.csv2("CTD_Kvavik_0424.csv")
CTD_Kvavik_0924<-read.csv2("CTD_kvavik_0924.csv")
CTD_Kvavik_1224<-read.csv2("CTD_kvavik_1224.csv")
CTD_Kollevoll_0924<-read.csv2("CTD_kollevoll_0924.csv")
CTD_Svartskjaer_0924<-read.csv2("CTD_svartskjaer_0924.csv")
CTD_Prestoyrenna_1224<-read.csv2("CTD_prestoyrenna_1224.csv")
CTD_Prestoyrenna_0524<-read.csv2("CTD_prestoyrenna_0524.csv")
```
adding location column
```{r}
CTD_Kvavik_0424$Location<-c("Kvavik")
CTD_Kvavik_0924$Location<-c("Kvavik")
CTD_Kvavik_1224$Location<-c("Kvavik")
CTD_Kollevoll_0924$Location<-c("Kollevoll")
CTD_Lok2_0424$Location<-c("LOK2")
CTD_Lok2_0924$Location<-c("LOK2")
CTD_Lok1_1224$Location<-c("LOK1")
CTD_Lok1_0924$Location<-c("LOK1")
CTD_MFS_0524$Location<-c("MFS")
CTD_MFS_0924$Location<-c("MFS")
CTD_MFS_1224$Location<-c("MFS")
CTD_Prestoyrenna_0524$Location<-c("Prestoyrenna")
CTD_Svartskjaer_0924$Location<-c("Svartskjaer")
CTD_Prestoyrenna_1224$Location<-c("Prestoyrenna")
```
selcting and renaming columns to match for later combination

```{r}
CTD_Kvavik_0924<-CTD_Kvavik_0924%>%
  select(c("Sal.","Cond.", "Temp", "fluorescence","OpOx..", "Date", "Location", "Press"))%>%
  rename("Depth" = "Press")
CTD_Kvavik_0424<-CTD_Kvavik_0424%>%
  select(c("Sal.","Cond.", "Temp", "fluorescence", "Date", "Location", "Press"))%>%
  rename("Depth" = "Press")
CTD_Kvavik_1224<-CTD_Kvavik_1224%>%
  select(c("Sal.","Cond.", "Temp", "fluorescence","OpOx..", "Date", "Location", "Press"))%>%
  rename("Depth" = "Press")
```

```{r}
CTD_Kollevoll_0924<-CTD_Kollevoll_0924%>%
  select(c("Sal.","Cond.", "Temp", "fluorescence","OpOx", "Date", "Location", "Press"))%>%
  rename("Depth" = "Press")%>%
  rename("OpOx.." = "OpOx")
CTD_Prestoyrenna_0524<-CTD_Prestoyrenna_0524%>%
  select(c("Sal.","Cond.", "Temp", "fluorescence", "Date", "Location", "Press"))%>%
  rename("Depth" = "Press")
CTD_Prestoyrenna_1224<-CTD_Prestoyrenna_1224%>%
  select(c("Sal.","Cond.", "Temp", "fluorescence","OpOx..", "Date", "Location", "Press"))%>%
  rename("Depth" = "Press")
CTD_Svartskjaer_0924<-CTD_Svartskjaer_0924%>%
  select(c("Sal.","Cond.", "Temp", "fluorescence","OpOx..", "Date", "Location", "Press"))%>%
  rename("Depth" = "Press")
```

```{r}
CTD_MFS_0924<-CTD_MFS_0924%>%
  select(c("Sal.","Cond.", "Temp", "fluorescence","OpOx..", "Date", "Location", "Press"))%>%
  rename("Depth" = "Press")
CTD_MFS_0524<-CTD_MFS_0524%>%
  select(c("Sal.","Cond.", "Temp", "fluorescence", "Date", "Location", "Press"))%>%
  rename("Depth" = "Press")
CTD_MFS_1224<-CTD_MFS_1224%>%
  select(c("Sal.","Cond.", "Temp", "fluorescence","OpOx..", "Date", "Location", "Press"))%>%
  rename("Depth" = "Press")
```

```{r}
CTD_Lok1_1224<-CTD_Lok1_1224%>%
  select(c("Sal.","Cond.", "Temp", "fluorescence","OpOx..", "Date", "Location", "Press"))%>%
  rename("Depth" = "Press")
CTD_Lok1_0924<-CTD_Lok1_0924%>%
  select(c("Sal.","Cond.", "Temp", "fluorescence", "Date", "Location", "Press"))%>%
  rename("Depth" = "Press")
CTD_Lok2_0924<-CTD_Lok2_0924%>%
  select(c("Sal.","Cond.", "Temp", "fluorescence","OpOx..", "Date", "Location", "Press"))%>%
  rename("Depth" = "Press")
CTD_Lok2_0424<-CTD_Lok2_0424%>%
  select(c("Sal.","Cond.", "Temp", "fluorescence", "Date", "Location", "Press"))%>%
  rename("Depth" = "Press")
```
making a list of the ctd files
```{r}
CTD_list <- list(CTD_Kollevoll_0924,CTD_Kvavik_0424,CTD_Kvavik_0924,CTD_Kvavik_1224, CTD_Lok1_0924,CTD_Lok1_1224,CTD_Lok2_0424,CTD_Lok2_0924,CTD_MFS_0524,CTD_MFS_0924,CTD_MFS_1224, CTD_Prestoyrenna_0524,CTD_Prestoyrenna_1224, CTD_Svartskjaer_0924)
```
df uten oxygen kolonnen får den og blir fylt med na 
```{r}
CTD_list <- lapply(CTD_list, function(df) {
  if (!"OpOx.." %in% colnames(df)) {
    df$`OpOx..` <- NA
  }
  return(df)
})
```

slår sammen alle filene
```{r}
CTD_2024 <- Reduce(function(x, y) full_join(x, y, by = c("Date","Location", "Depth", "Sal.", "Cond.", "Temp", "fluorescence", "OpOx..")), CTD_list)
```

```{r}
CTD_2024$fluorescence[CTD_2024$fluorescence < 0] <- NA
CTD_2024$OpOx..[CTD_2024$OpOx.. < 0] <- NA
```

```{r}
write.csv2(CTD_2024, "CTD_2024.csv")
```

```{r}
#to average the values for each depth for further statistical analysis
average_ctd_in_bin <- function(df, bin_width = 1) {
  # Removing unwanted depths 
  df <- df %>% filter(Depth >= 0 & Depth <= max(Depth, na.rm = TRUE))
  
  # creating depth bins for the closest whole meter
  df$Depth_bin <- round(df$Depth / bin_width) * bin_width
  
  # grouping date, depth and location
  summarized_df <- df %>%
    group_by(Date, Location, Depth_bin) %>%
    summarize(
      Salinity = mean(Sal., na.rm = TRUE),
      Temperature = mean(Temp, na.rm = TRUE),
      Conductivity = mean(Cond., na.rm = TRUE),
      Oxygen = mean(OpOx.., na.rm = TRUE),
      Fluorescence = mean(fluorescence, na.rm = TRUE),
      .groups = "drop"
    )
  
  
  summarized_df <- summarized_df %>% arrange(Date, Location, Depth_bin)
  
  return(summarized_df)
}
#using the function on the combined CTD file 
CTD_2024_avg <- average_ctd_in_bin(CTD_2024)

head(CTD_2024_avg)
```


